export const queryKeys = {
  weeklyNotes: ['weekly-notes'] as const,
  weeklyReviews: ['weekly-reviews'] as const,
  actionAlignmentScores: ['action-alignment-scores'] as const,
  weeklyReviewAssistantStatus: ['weekly-review-assistant-status'] as const,
  providerStatus: ['provider-status'] as const,
  providerConfig: ['provider-config'] as const,
  productStatus: ['product-status'] as const,
  localAppStatus: ['local-app-status'] as const,
  runtimeStatus: ['runtime-status'] as const,
  alters: ['alters'] as const,
  calibrationHistory: ['calibration-history'] as const,
  patternReviews: ['pattern-reviews'] as const,
  patternReviewDetail: (reviewId: string | null) => ['pattern-review', reviewId] as const,
  behaviorValidation: ['behavior-validation'] as const,
  dataManifest: ['data-manifest'] as const,
  trendAnalysis: (lookbackWeeks: number, forecastWeeks: number) => ['trend-analysis', lookbackWeeks, forecastWeeks] as const,
  dynamicWeights: (lookbackWeeks: number) => ['dynamic-weights', lookbackWeeks] as const,
  patternAdjustment: (lookbackWeeks: number, forecastWeeks: number) => ['pattern-adjustment', lookbackWeeks, forecastWeeks] as const,
  predictorProfiles: ['predictor-profiles'] as const,
  predictorProfile: (profileId: string | null) => ['predictor-profile', profileId] as const,
  outcomeTargets: ['outcome-targets'] as const,
  forecastSnapshots: ['forecast-snapshots'] as const,
  externalEvidence: ['external-evidence'] as const,
  forecastEvaluations: ['forecast-evaluations'] as const,
  forecastScorecard: ['forecast-scorecard'] as const,
  publicPriorArtifacts: ['public-prior-artifacts'] as const,
  publicPriorModelCards: ['public-prior-model-cards'] as const,
  publicPriorCoverage: ['public-prior-coverage'] as const,
  calibrationConversations: ['calibration-conversations'] as const,
  calibrationConversation: (id: string | null) => ['calibration-conversation', id] as const,
  calibrationDrafts: ['calibration-drafts'] as const,
  behaviorMetricsRecords: ['behavior-metrics-records'] as const,
} as const
